blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/hay-chess/hay-chess-tracker/security/advisories/new
    about: Report a security vulnerability (DO NOT open a public issue)
  - name: Question / Discussion
    url: https://github.com/hay-chess/hay-chess-tracker/discussions
    about: Ask questions or discuss ideas
  - name: Documentation
    url: https://github.com/hay-chess/hay-chess-tracker/tree/master/docs
    about: Read the documentation
